
CREATE SEQUENCE MIGI.SQ_GENM_USUARIO MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 2 INCREMENT BY 1;
CREATE SEQUENCE MIGI.SQ_GENM_ANIO MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE MIGI.SQ_GENM_EQUIPO MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 2 INCREMENT BY 1;
CREATE SEQUENCE MIGI.SQ_GENM_PALABRA_CLAVE MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 4 INCREMENT BY 1;
CREATE SEQUENCE MIGI.SQ_GENM_PALABRA_CLAVE_CANTIDAD MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 2 INCREMENT BY 1;
CREATE SEQUENCE MIGI.SQ_GENM_EXCEL MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MIGI.SQ_GENM_RESULTADO MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MIGI.SQ_GEND_RESULTADO_PALABRA_CLAV MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MIGI.SQ_GEND_RESULTADO_PALABRA_CANT MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MIGI.SQ_GEND_RESULTADO_ANIO MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 INCREMENT BY 1;

CREATE TABLE T_MAE_ROL(
ID_ROL NUMBER,
NOMBRE VARCHAR2(50),
FLAG_ESTADO VARCHAR2(1) DEFAULT '1',
REG_USUARIO NUMBER,
REG_FECHA DATE DEFAULT SYSDATE,
UPD_USUARIO NUMBER,
UPD_FECHA DATE,
CONSTRAINT ROL_PK PRIMARY KEY (ID_ROL)
);

CREATE TABLE T_GENM_USUARIO (
ID_USUARIO NUMBER,
CORREO VARCHAR2(100),
NOMBRES VARCHAR2(250),
APELLIDOS VARCHAR2(250),
CONTRASENA VARCHAR2(100),
ID_ROL NUMBER,
FLAG_ESTADO VARCHAR2(1) DEFAULT '1',
REG_USUARIO NUMBER,
REG_FECHA DATE DEFAULT SYSDATE,
UPD_USUARIO NUMBER,
UPD_FECHA DATE,
PRIMARY KEY (ID_USUARIO),
FOREIGN KEY (ID_ROL) REFERENCES T_MAE_ROL (ID_ROL)
);

CREATE TABLE T_GENM_EQUIPO (
ID_EQUIPO NUMBER PRIMARY KEY,
EQUIPO VARCHAR2(1000),
FLAG_ESTADO VARCHAR2(1) DEFAULT '1',
REG_USUARIO NUMBER,
REG_FECHA DATE DEFAULT SYSDATE,
UPD_USUARIO NUMBER,
UPD_FECHA DATE
); --DROP TABLE T_GENM_PALABRAS_CLAVE


CREATE TABLE T_GENM_PALABRA_CLAVE (
ID_PALABRA NUMBER PRIMARY KEY,
PALABRA VARCHAR2(1000),
ID_EQUIPO NUMBER,
FLAG_ESTADO VARCHAR2(1) DEFAULT '1',
REG_USUARIO NUMBER,
REG_FECHA DATE DEFAULT SYSDATE,
UPD_USUARIO NUMBER,
UPD_FECHA DATE
); --DROP TABLE T_GENM_PALABRA_CLAVE

CREATE TABLE T_GENM_PALABRA_CLAVE_CANTIDAD (
ID_PALABRA_CANTIDAD NUMBER PRIMARY KEY,
PALABRA_CANTIDAD VARCHAR2(1000),
FLAG_ESTADO VARCHAR2(1) DEFAULT '1',
REG_USUARIO NUMBER,
REG_FECHA DATE DEFAULT SYSDATE,
UPD_USUARIO NUMBER,
UPD_FECHA DATE
); --DROP TABLE T_GENM_PALABRA_CLAVE_CANTIDAD

CREATE TABLE T_GENM_ANIO (
ID_ANIO NUMBER PRIMARY KEY,
ANIO VARCHAR2(1000),
FLAG_ESTADO VARCHAR2(1) DEFAULT '1',
REG_USUARIO NUMBER,
REG_FECHA DATE DEFAULT SYSDATE,
UPD_USUARIO NUMBER,
UPD_FECHA DATE
);--DROP TABLE T_GENM_ANIO

CREATE TABLE T_GENM_MIGI(
ANIO VARCHAR2(40),
MES VARCHAR2(40),
ENTIDAD VARCHAR2(4000),
RUC_ENTIDAD VARCHAR2(4000),
FECHA_REGISTRO VARCHAR2(4000),
FECHA_DE_EMISION VARCHAR2(4000),
FECHA_COMPROMISO_PRESUPUESTAL VARCHAR2(4000),
FECHA_DE_NOTIFICACION VARCHAR2(4000),
TIPOORDEN VARCHAR2(4000),
NRO_DE_ORDEN VARCHAR2(4000),
ORDEN VARCHAR2(4000),
DESCRIPCION_ORDEN VARCHAR2(4000),
MONEDA VARCHAR2(4000),
MONTO_TOTAL_ORDEN_ORIGINAL VARCHAR2(4000),
OBJETOCONTRACTUAL VARCHAR2(4000),
ESTADOCONTRATACION VARCHAR2(4000),
TIPODECONTRATACION VARCHAR2(4000),
DEPARTAMENTO__ENTIDAD VARCHAR2(4000),
RUC_CONTRATISTA VARCHAR2(4000),
NOMBRE_RAZON_CONTRATISTA VARCHAR2(4000)
);--DROP TABLE T_GENM_MIGI

CREATE TABLE T_GENM_MIGI_M8U(
VERSION VARCHAR2(400),
ENTIDAD_RUC VARCHAR2(4000),
ENTIDAD VARCHAR2(4000),
MODALIDAD VARCHAR2(4000),
PROCESO_SELECCION VARCHAR2(4000),
CODIGOCONVOCATORIA VARCHAR2(4000),
PROCESO VARCHAR2(4000),
FECHA_CONVOCATORIA VARCHAR2(4000),
OBJETO_CONTRACTUAL VARCHAR2(4000),
DESCRIPCION_PROCESO VARCHAR2(4000),
MONEDA VARCHAR2(4000),
MONTO_REFERENCIAL_PROCESO VARCHAR2(4000),
ITEM VARCHAR2(4000),
N_ITEM VARCHAR2(4000),
DESCRIPCION_ITEM VARCHAR2(4000),
MONTO_REFERENCIAL_ITEM VARCHAR2(4000),
MONTO_ADJUDICADO_ITEM VARCHAR2(4000),
CANTIDAD_ADJUDICADO_ITEM VARCHAR2(4000),
CODIGORUC_PROVEEDOR VARCHAR2(4000),
PROVEEDOR VARCHAR2(4000),
FECHA_BUENAPRO VARCHAR2(4000),
CONSORCIO VARCHAR2(4000),
RUC_MIEMBRO VARCHAR2(4000),
MIEMBRO VARCHAR2(4000),
PAQUETE VARCHAR2(4000),
CODIGOGRUPO VARCHAR2(4000),
GRUPO VARCHAR2(4000),
CODIGOFAMILIA VARCHAR2(4000),
FAMILIA VARCHAR2(4000),
CODIGOCLASE VARCHAR2(4000),
CLASE VARCHAR2(4000),
CODIGOCOMMODITY VARCHAR2(4000),
COMMODITY VARCHAR2(4000),
CODIGO_ITEM VARCHAR2(4000),
ITEM_CUBSO VARCHAR2(4000),
ESTADO_ITEM VARCHAR2(4000)
);--DROP TABLE T_GENM_MIGI_M8U

CREATE TABLE T_MAE_TIPO_EXCEL(
ID_TIPO_EXCEL NUMBER PRIMARY KEY,
DESCRIPCION VARCHAR2(100)
); --DROP TABLE T_MAE_TIPO_EXCEL

CREATE TABLE T_GENM_EXCEL(
ID_EXCEL NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(1000),
ANIO VARCHAR2(1000),
MES VARCHAR2(1000),
ID_TIPO_EXCEL NUMBER,
FLAG_ESTADO VARCHAR2(1) DEFAULT '1',
REG_USUARIO NUMBER,
REG_FECHA DATE DEFAULT SYSDATE,
UPD_USUARIO NUMBER,
UPD_FECHA DATE,
FOREIGN KEY (ID_TIPO_EXCEL) REFERENCES T_MAE_TIPO_EXCEL (ID_TIPO_EXCEL)
); --DROP TABLE T_GENM_EXCEL

CREATE TABLE T_GENM_RESULTADO(
ID_RESULTADO NUMBER,
ID_TIPO_BUSQUEDA NUMBER,
ID_USUARIO NUMBER,
FLAG_ESTADO VARCHAR2(1) DEFAULT '1',
REG_USUARIO NUMBER,
REG_FECHA DATE DEFAULT SYSDATE,
UPD_USUARIO NUMBER,
UPD_FECHA DATE,
PRIMARY KEY (ID_RESULTADO)
);--T_GENM_RESULTADO

CREATE TABLE T_GEND_RESULTADO_PALABRA_CLAVE(
ID_PALABRA_RESULTADO NUMBER,
ID_RESULTADO NUMBER,
PALABRA VARCHAR2(100),
ID_USUARIO NUMBER,
FLAG_ESTADO VARCHAR2(1) DEFAULT '1',
REG_USUARIO NUMBER,
REG_FECHA DATE DEFAULT SYSDATE,
UPD_USUARIO NUMBER,
UPD_FECHA DATE,
PRIMARY KEY (ID_PALABRA_RESULTADO),
FOREIGN KEY (ID_RESULTADO) REFERENCES T_GENM_RESULTADO (ID_RESULTADO)
);--T_GEND_RESULTADO_PALABRA_CLAVE

CREATE TABLE T_GEND_RESULTADO_PALABRA_CANT(
ID_PALABRA_CANT_RESULTADO NUMBER,
ID_RESULTADO NUMBER,
PALABRA_CANTIDAD VARCHAR2(100),
ID_USUARIO NUMBER,
FLAG_ESTADO VARCHAR2(1) DEFAULT '1',
REG_USUARIO NUMBER,
REG_FECHA DATE DEFAULT SYSDATE,
UPD_USUARIO NUMBER,
UPD_FECHA DATE,
PRIMARY KEY (ID_PALABRA_CANT_RESULTADO),
FOREIGN KEY (ID_RESULTADO) REFERENCES T_GENM_RESULTADO (ID_RESULTADO)
);--T_GEND_RESULTADO_PALABRA_CANT

CREATE TABLE T_GEND_RESULTADO_ANIO(
ID_ANIO_RESULTADO NUMBER,
ID_RESULTADO NUMBER,
ANIO VARCHAR2(100),
ID_USUARIO NUMBER,
FLAG_ESTADO VARCHAR2(1) DEFAULT '1',
REG_USUARIO NUMBER,
REG_FECHA DATE DEFAULT SYSDATE,
UPD_USUARIO NUMBER,
UPD_FECHA DATE,
PRIMARY KEY (ID_ANIO_RESULTADO),
FOREIGN KEY (ID_RESULTADO) REFERENCES T_GENM_RESULTADO (ID_RESULTADO)
);--T_GEND_RESULTADO_ANIO

INSERT INTO T_MAE_ROL (ID_ROL, NOMBRE, REG_USUARIO) VALUES (1, 'Especialista', 0);

--T_GENM_USUARIO
INSERT INTO T_GENM_USUARIO (ID_USUARIO, NOMBRES, APELLIDOS, CORREO, CONTRASENA, ID_ROL, REG_USUARIO)
VALUES (1, 'Carlos', 'Galdos', 'carlos@grupo-zuniga.com', 'Flavio2019', 1, 1);

--T_GENM_EQUIPO
INSERT INTO T_GENM_EQUIPO (ID_EQUIPO, EQUIPO) VALUES (1, 'VEHICULO');

--T_GENM_PALABRAS_CLAVE
INSERT INTO T_GENM_PALABRA_CLAVE (ID_PALABRA, PALABRA, ID_EQUIPO) VALUES (1, 'COMBUSTIBLE', 1);
INSERT INTO T_GENM_PALABRA_CLAVE (ID_PALABRA, PALABRA, ID_EQUIPO) VALUES (2, 'ADQUISICION', 1);
INSERT INTO T_GENM_PALABRA_CLAVE (ID_PALABRA, PALABRA, ID_EQUIPO) VALUES (3, 'BATERIA', 1);

--T_GENM_PALABRAS_CLAVE_CANTIDAD
INSERT INTO T_GENM_PALABRA_CLAVE_CANTIDAD (ID_PALABRA_CANTIDAD, PALABRA_CANTIDAD) VALUES (1, 'ADQUISICION DE');

--TABLE T_GENM_ANIO
INSERT INTO T_GENM_ANIO (ID_ANIO, ANIO) VALUES (1, '2015');
INSERT INTO T_GENM_ANIO (ID_ANIO, ANIO) VALUES (2, '2016');
INSERT INTO T_GENM_ANIO (ID_ANIO, ANIO) VALUES (3, '2017');
INSERT INTO T_GENM_ANIO (ID_ANIO, ANIO) VALUES (4, '2018');
INSERT INTO T_GENM_ANIO (ID_ANIO, ANIO) VALUES (5, '2019');
INSERT INTO T_GENM_ANIO (ID_ANIO, ANIO) VALUES (6, '2020');
INSERT INTO T_GENM_ANIO (ID_ANIO, ANIO) VALUES (7, '2021');
INSERT INTO T_GENM_ANIO (ID_ANIO, ANIO) VALUES (8, '2022');
INSERT INTO T_GENM_ANIO (ID_ANIO, ANIO) VALUES (9, '2023');

--TABLE T_MAE_TIPO_EXCEL
INSERT INTO T_MAE_TIPO_EXCEL (ID_TIPO_EXCEL, DESCRIPCION) VALUES (1, 'Menor a 8 UIT');
INSERT INTO T_MAE_TIPO_EXCEL (ID_TIPO_EXCEL, DESCRIPCION) VALUES (2, 'Mayor o igual a 8 UIT');

COMMIT;